apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: device-random
  name: device-random
spec:
  type: LoadBalancer
  ports:
  - name: "49988"
    port: 49988
    targetPort: 49988
  selector:
    io.kompose.service: device-random
status:
  loadBalancer: {}