apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: edgex-core-data
  name: edgex-core-data
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: edgex-core-data
    spec:
      containers:
      - image: edgexfoundry/docker-core-data-go:0.7.1
        name: edgex-core-data
        ports:
        - containerPort: 48080
        - containerPort: 5563
        resources: {}
        command: ["/core-data","--profile=docker","--confdir=/res"]
        volumeMounts:
        - mountPath: /data/db
          name: data-db
        - mountPath: /edgex/logs
          name: edgex-logs
        - mountPath: /consul/config
          name: consul-config
        - mountPath: /consul/data
          name: consul-data
      restartPolicy: Always
      hostname: edgex-core-data
      volumes:
      - name: data-db
        hostPath:
          path: /data/db
      - name: edgex-logs
        hostPath:
          path: /edgex/logs
      - name: consul-config
        hostPath:
          path: /consul/config
      - name: consul-data
        hostPath:
          path: /consul/data
status: {}
