apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: edgex-export-distro
  name: edgex-export-distro
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: edgex-export-distro
    spec:
      containers:
      - image: edgexfoundry/docker-export-distro-go:0.7.1
        name: edgex-export-distro
        ports:
        - containerPort: 48070
        - containerPort: 5566
        resources: {}
        command: ["/export-distro","--profile=docker","--confdir=/res"]
        volumeMounts:
        - mountPath: /data/db
          name: data-db
        - mountPath: /edgex/logs
          name: edgex-logs
        - mountPath: /consul/config
          name: consul-config
        - mountPath: /consul/data
          name: consul-data
      restartPolicy: Always
      hostname: edgex-export-distro
      volumes:
      - name: data-db
        hostPath:
          path: /data/db
      - name: edgex-logs
        hostPath:
          path: /edgex/logs
      - name: consul-config
        hostPath:
          path: /consul/config
      - name: consul-data
        hostPath:
          path: /consul/data
status: {}
