apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: edgex-ui
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
      - image: edgexfoundry/docker-edgex-ui-go:0.1.1
        name: edgex-ui-go
        ports:
        - containerPort: 4000
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: db-data
        - mountPath: /edgex/logs
          name: log-data
        - mountPath: /consul/config
          name: consul-config
        - mountPath: /consul/data
          name: consul-data
      #hostname: edgex-ui-go
      restartPolicy: Always
      volumes:
      - name: db-data
        hostPath:
          path: /data/db
      - name: log-data
        hostPath:
          path: /edgex/logs
      - name: consul-config
        hostPath:
          path: /consul/config
      - name: consul-data
        hostPath:
          path: /consul/data
status: {}
